### ISSUE TITLE
[Suggestion] A simpler solution with css-counters 

### ISSUE THREAD

**Issue by anandkumar89** [onlyafly/number-headings-obsidian#51]
```css
/** Numbered Headings **/
.cm-content { counter-reset: h1counter h2counter h3counter h4counter h5counter h6counter; }

.HyperMD-header-1 { counter-reset: h2counter; }
.HyperMD-header-2 { counter-reset: h3counter; }
.HyperMD-header-3 { counter-reset: h4counter; }
.HyperMD-header-4 { counter-reset: h5counter; }
.HyperMD-header-5 { counter-reset: h6counter; }


.HyperMD-header-1::before {
counter-increment: h1counter;
content: counter(h1counter) ".\0000a0\0000a0";
}

.HyperMD-header-2:before {
    counter-increment: h2counter;
    content: counter(h1counter) "." counter(h2counter) ".\0000a0\0000a0";
}
.HyperMD-header-3:before {
    counter-increment: h3counter;
    content: counter(h1counter) "." counter(h2counter) "." counter(h3counter) ".\0000a0\0000a0";
}

.HyperMD-header-4:before {
    counter-increment: h4counter;
    content: counter(h1counter) "." counter(h2counter) "." counter(h3counter) "." counter(h4counter) ".\0000a0\0000a0";
}

.HyperMD-header-5:before {
    counter-increment: h5counter;
    content: counter(h1counter) "." counter(h2counter) "." counter(h3counter) "." counter(h4counter) "." counter(h5counter) ".\0000a0\0000a0";
}

.HyperMD-header-6:before {
    counter-increment: h6counter;
    content: counter(h1counter) "." counter(h2counter) "." counter(h3counter) "." counter(h4counter) "." counter(h5counter) "." counter(h6counter) ".\0000a0\0000a0";
}
```

preview : 
<img width="324" alt="Screenshot 2023-06-13 at 4 19 44 AM" src="https://github.com/onlyafly/number-headings-obsidian/assets/12571250/8dd3ad3e-f667-4b1c-b3ef-98bf0fed1cd4">
